application:
  name: bookshop

spring:
  boot:
    admin:
      client:
        url: http://localhost:9091/

server:
  port: 9443
#  ssl:
#    key-store: services_module/src/main/resources/keystore.p12
#    key-store-password: ENC(ke19FwcccY7RRC1iaavIaL4u9SOQETKk)
#    keyStoreType: PKCS12
#    keyAlias: tomcat

jasypt:
  encryptor:
    password: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false